services:
  kasa:
    build: .
    image: kasa:latest
    restart: unless-stopped 
    ports:
      - "${FRONTEND_PORT:-8082}:${FRONTEND_PORT:-8082}"
    env_file:
      - path: .env
        required: false
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT:-8082}
      - BACKEND_PORT=${BACKEND_PORT:-8000}
      - JWT_SECRET=${JWT_SECRET:-replace-me-with-a-super-dupper-secret-phrase}
    volumes:
      - kasa_db:/kasa/backend/data
volumes:
  kasa_db: